export enum TokenType {
  PALABRA_RESERVADA = 'PALABRA_RESERVADA',
  IDENTIFICADOR = 'IDENTIFICADOR',
  NUMERO = 'NUMERO',
  CADENA = 'CADENA',
  OPERADOR = 'OPERADOR',
  DESCONOCIDO = 'DESCONOCIDO',
}
