export enum TokenType {
  PALABRA_RESERVADA = 'PALABRA_RESERVADA',
  TIPO_DATO = 'TIPO_DATO',
  IDENTIFICADOR = 'IDENTIFICADOR',
  NUMERO = 'NUMERO',
  CADENA = 'CADENA',
  BOOLEANO = 'BOOLEANO',
  ASIGNACION = 'ASIGNACION',
  OPERADOR_RELACIONAL = 'OPERADOR_RELACIONAL',
  NUEVA_LINEA = 'NUEVA_LINEA',
  DESCONOCIDO = 'DESCONOCIDO',
}
